stages:
  - build
  - deploy

variables:
  HARBOR_REGISTRY: "ic-registry.epfl.ch"
  APPLICATION_NAME: "cs250" 
  REPO_NAME: "cs250"
  IMAGE_NAME: "cs250"
  TAG: "test"
  REGISTRY_ROBOT: 'robot$$CS250-gitlab'
  DOCKERFILE_PATH: "prod.Dockerfile"
  DOCKER_AUTH_CONFIG: "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$REGISTRY_ROBOT\",\"password\":\"$HARBOR_PASSWORD\"}}}"
  FQDN: cs250.epfl.ch

.EXEC_SCRIPT: &EXEC_SCRIPT
  - mkdir -p ~/.kube
  - echo "$KUBERNETESCONFIG" > ~/.kube/config
  - kubectl delete secret $APPLICATION_NAME-regcred --ignore-not-found -n thl2
  - kubectl create secret docker-registry $APPLICATION_NAME-regcred --docker-server="$HARBOR_REGISTRY" --docker-username=$REGISTRY_ROBOT --docker-password="$HARBOR_PASSWORD" --docker-email=support-icit@epfl.ch -n thl2
  - sed -i "s%APPLICATION-HOSTS-FQDN%$FQDN%g" $CI_PROJECT_DIR/k8s/ingress.yaml
  - sed -i "s%APPLICATION-IMAGE%$HARBOR_REGISTRY/$REPO_NAME/$IMAGE_NAME:$TAG%g" $CI_PROJECT_DIR/k8s/deployment.yaml
  - sed -i "s%APPLICATION-NAME%$APPLICATION_NAME%g" $CI_PROJECT_DIR/k8s/deployment.yaml
  - sed -i "s%APPLICATION-NAME%$APPLICATION_NAME%g" $CI_PROJECT_DIR/k8s/ingress.yaml
  - sed -i "s%APPLICATION-NAME%$APPLICATION_NAME%g" $CI_PROJECT_DIR/k8s/persistentvolume.yaml
  - sed -i "s%APPLICATION-NAME%$APPLICATION_NAME%g" $CI_PROJECT_DIR/k8s/persistentvolumeclaim.yaml
  - sed -i "s%APPLICATION-NAME%$APPLICATION_NAME%g" $CI_PROJECT_DIR/k8s/service.yaml
  - kubectl apply -f $CI_PROJECT_DIR/k8s/ingress.yaml -n thl2
  - kubectl apply -f $CI_PROJECT_DIR/k8s/persistentvolumeclaim.yaml -n thl2
  - kubectl apply -f $CI_PROJECT_DIR/k8s/service.yaml -n thl2
  - kubectl delete -f $CI_PROJECT_DIR/k8s/deployment.yaml --ignore-not-found -n thl2
  - kubectl apply -f $CI_PROJECT_DIR/k8s/deployment.yaml -n thl2


build-a-docker:
  stage: build
  only:
    refs:
      - main

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - env
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/$DOCKERFILE_PATH --destination $HARBOR_REGISTRY/$REPO_NAME/$APPLICATION_NAME:$TAG --build-arg CONVEX_DEPLOY_KEY=$CONVEX_DEPLOY_KEY --build-arg COMPRESS_API_KEY=$COMPRESS_API_KEY --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN --build-arg BASE_URL=$BASE_URL --build-arg "JWT_KEY='$JWT_KEY'" --build-arg IDENTIFIER_SALT=$IDENTIFIER_SALT

deploy-to-prod:
  stage: deploy
  when: manual

  image:
    name: ic-registry.epfl.ch/tools/helm-kubectl-docker:latest
    entrypoint: [""]
  script:
    - *EXEC_SCRIPT
