apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPLICATION-NAME-app
  labels:
    name: APPLICATION-NAME-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: APPLICATION-NAME-app
  template:
    metadata:
      labels:
        name: APPLICATION-NAME-app
    spec:
      containers:
      - name: APPLICATION-NAME-app
        imagePullPolicy: Always
        image: APPLICATION-IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: EXAMPLE
          value: "Your example value"
        volumeMounts:
        - mountPath: /app/drizzle/storage
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: PVC_NAME
      restartPolicy: Always
