---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cs250
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ic1files.epfl.ch
    path: "/u10394_ic_icit_003_files_nfs/cs250.epfl.ch"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cs250
  namespace: thl2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
