---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: PVC_NAME
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: PVC_SERVER
    path: PVC_PATH
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: PVC_NAME
  namespace: PVC_NSPACE
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
